sulu_core:
    locales:
        en: English
        fr: French
    translations:
        - en
        - fr
sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
    resources:
        reportings:
            routes:
                list: app.get_reporting_list
                detail: app.get_reporting
